### PR TITLE
add vscode repo

### PR DESCRIPTION
**Pull request by Boshen**

### CODE REVIEW

**Comment by Boshen** [comment]
Still failing :-(

**Comment by rzvxa** [comment]
I'll take care of it

**Comment by rzvxa** [comment]
@Boshen I've run the tests again and no sign of false positives, There are some rules-of-hooks errors but I think they are all expected. I guess from the day you created this PR till now I've fixed it, We can track the last CI run checkout commit if you want to know which change resulted in it being fixed.

**Comment by Boshen** [comment]
include the other cfg rules

**Comment by rzvxa** [comment]
I think all `no-fallthrough` diagnostics are accurate, I'll investigate them right away.
As for `getter-return` false positives I'm working on them in this PR https://github.com/oxc-project/oxc/pull/3714, If I'm not mistaken this particular one is already fixed, I'll check it out and if it is I'll extract it to its own PR so it can be merged sooner.

**Comment by rzvxa** [comment]
you should merge this first https://github.com/oxc-project/oxc/pull/3714

**Pull request merged**
